# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    main.yml                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mbah <mbah@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/14 01:23:55 by mbah              #+#    #+#              #
#    Updated: 2024/12/14 01:24:13 by mbah             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Exécute tous les jours à minuit
  workflow_dispatch: # Permet une exécution manuelle

jobs:
  generate-snake:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2.2.1
        with:
          github_user_name: mbah24-dev
          outputs: dist

      - name: Add Snake to the repository
        run: |
          mv dist/github-contribution-grid-snake.svg ./
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Mise à jour : Animation Snake"
          git push
