# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    main.yml                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mbah <mbah@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/14 01:23:55 by mbah              #+#    #+#              #
#    Updated: 2024/12/14 01:24:13 by mbah             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # S'exécute tous les jours à minuit
  workflow_dispatch: # Permet d'exécuter manuellement
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Générer Snake
        uses: Platane/snk@v2
        with:
          github_user_name: mbah24-dev
          outputs: dist

      - name: Ajouter Snake au dépôt
        uses: actions/upload-artifact@v3
        with:
          name: snake-graph
          path: dist

      - name: Déployer l'animation Snake
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Mise à jour : Animation Snake"
          git push

